version: '3.9'
services:
  web:
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_TOKEN_IN_BODY=${REFRESH_TOKEN_IN_BODY}
      - REFRESH_TOKEN_IN_COOKIE=${REFRESH_TOKEN_IN_COOKIE}
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - blog_data:/va/lib/postgresql/data/

volumes:
  blog_data: